image: trion/ng-cli

include:
  template: Dependency-Scanning.gitlab-ci.yml

cache:
  untracked: true
  paths:
    - node_modules/

stages:
  - build
  - deploy
  

build:
  stage: build
  script:
    - npm install
    - ng build --prod
  artifacts:
    paths:
      - dist
  only:
    - master
  tags:
    - nodeJS

deploy:
  stage: deploy
  script:
    - npm i -g netlify-cli
    - netlify deploy --site $NETLIFY_SITE_ID --auth $NETLIFY_AUTH_TOKEN --prod
  dependencies:
    - build
  only:
    - master
  tags:
    - nodeJS
