before_script:
  - npm install

cache:
  untracked: true
  paths:
    - node_modules/

stages:
  - build
  - test
  - deploy
  

build:
  image: trion/ng-cli
  stage: build
  script:
    - ng build --prod
  artifacts:
    paths:
      - dist
  only:
    - master
  tags:
    - nodeJS
  
test:
  image: trion/ng-cli-karma
  stage: test
  script:
    - ng test
  only:
    - master
  tags:
    - nodeJS

deploy:
  image: trion/ng-cli
  stage: deploy
  script:
    - npm i -g netlify-cli
    - netlify deploy --site $NETLIFY_SITE_ID --auth $NETLIFY_AUTH_TOKEN --prod
  dependencies:
    - build
  only:
    - master
  tags:
    - nodeJS
